swagger: '2.0'
info:
  description: 'API for managing notes with JWT authentication'
  title: 'Notes API'
  version: '1.0'
host: 'localhost:8080'
basePath: '/'
paths:
  /login:
    post:
      description: 'Authenticate user and return JWT token'
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - auth
      summary: 'User login'
      parameters:
        - description: 'User credentials'
          name: credentials
          in: body
          required: true
          schema:
            $ref: '#/definitions/models.User'
      responses:
        200:
          description: 'OK'
          schema:
            type: string
        401:
          description: 'Unauthorized'
  /notes:
    get:
      security:
        - BearerAuth: []
      description: 'Get all notes for the authenticated user'
      produces:
        - application/json
      tags:
        - notes
      summary: 'Get user notes'
      responses:
        200:
          description: 'OK'
          schema:
            type: array
            items:
              $ref: '#/definitions/models.Note'
        401:
          description: 'Unauthorized'
    post:
      security:
        - BearerAuth: []
      description: 'Create a new note for the authenticated user'
      consumes:
        - application/json
      produces:
        - application/json
      tags:
        - notes
      summary: 'Create a new note'
      parameters:
        - description: 'Note body'
          name: note
          in: body
          required: true
          schema:
            $ref: '#/definitions/models.Note'
      responses:
        201:
          description: 'Created'
        401:
          description: 'Unauthorized'
definitions:
  models.Note:
    type: object
    properties:
      id:
        type: integer
      user_id:
        type: integer
      body:
        type: string
  models.User:
    type: object
    properties:
      id:
        type: integer
      username:
        type: string
      password:
        type: string
securityDefinitions:
  BearerAuth:
    type: apiKey
    name: Authorization
    in: header